export const TRANSITION_DURATION = 0.8;
export const LONG_PRESS_DURATION = 600;

export interface Note {
  id: number;
  from: string;
  text: string;
  fullText: string;
  photo: string;
  color: string;
}

export const NOTES: Note[] = [
  { id: 1, from: "Satvik", text: "To our AAREY RUNCLUB and much more!", fullText: "Ever since that first runclub morning in Nov ’24, I’ve admired how seriously you show up — even sleeping by 8–10pm just so you never miss a run. It's crazy to see how consistent you are. 🏃‍♀️ Canada’s getting an amazing runner (and human). I’m really going to miss our runs, but I’m so excited to see you chase bigger miles there. 💛🇨🇦", photo: "/photos/satvik.png", color: "hsl(270,30%,40%)" },
  { id: 2, from: "Tanvi", text: "INUA's bestest there is", fullText: "So glad i met you at inua that day! didn’t know we’d become fast friends but i think that’s what happens when you’re the only 2 girls at a run club, hopefully that changes soon :( Wishing you all the best, wish we had met sooner and had time to go for more runs and coffee, could use the company to roast Akrit! To many more marathons! Love,", photo: "/photos/tanvi.png", color: "hsl(270,30%,40%)" },
  { id: 3, from: "Esha", text: "COME BACK SOON😭", fullText: "Anushri you sweet chirpy birdie with the most infectious energy, I’m going to miss you so much!💓", photo: "/photos/esha.png", color: "hsl(270,30%,40%)" },
  { id: 4, from: "Maanya", text: "Needed more swimming plans", fullText: "It’s hard to believe it’s time to say goodbye. I’ll always be grateful for the memories we made  especially swimming, and that unforgettable karaoke night where we sang our hearts out (even when we were completely off-key 😄). I wish you could have come to Mangalore as well🥺 Thank you for the joy, the laughter, and the moments that turned into beautiful memories. Wishing you happiness, success, and amazing new adventures ahead. Don’t forget, wherever you go, you’ve got a friend cheering for you. 💙 Love", photo: "/photos/maanya.png", color: "hsl(270,30%,40%)" },
  { id: 5, from: "Anushri", text: "'Not a goodbye, more like SEE YOU SOON!'", fullText: "I remember the first time I met you, I was genuinely so inspired by you that I called myself a fan. And guess what? It still holds true. I refuse to believe we didn’t meet more often. So, see you soon Anushri 🫶", photo: "/photos/anushri.png", color: "hsl(270,30%,40%)" },
  { id: 6, from: "Akrit", text: "The GOATest of all goats", fullText: "Anushriii you shall be dearly missed at every run, post hangout, race, and beer scene (way more than you)know for the longest time! Until we meet again, keep safe, be happy, stay blessed, and keep smiling always! 👸🏻🧿", photo: "/photos/akrit.png", color: "hsl(270,30%,40%)" },
  { id: 7, from: "Anjali", text: "Chammak to my Challo ANUSHRI! My Bombay Baddie.", fullText: "You and shree are literally the best part of my time in India- I’m so glad we were able to get close and experience living away from home together. You’re the best ever and I’m so excited to spend time with you anywhere in the world :) <3", photo: "/photos/anjali.png", color: "hsl(270,30%,40%)" },
  { id: 8, from: "Karthik", text: "How one runclub friendship turned so good", fullText: "Anushriii, Can’t believe you’re heading back to Canada already! Mumbai’s going to miss your goofy, energetic vibe and all the fun you brought with you, running rockstar. What a great stint in India filled with amazing memories most of all our runs, the Lonavala trip, and the Karaoke jams. Wouldn’t trade those moments (or miles) for anything. See you at the next start line. 🏃‍♀️✨ ", photo: "/photos/karthik.png", color: "hsl(270,30%,40%)" },
  { id: 9, from: "Om", text: "Canadian PICASSO !!!", fullText: "I don’t really have a photo, but this is a screenshot from a video of the moment when you accidentally dipped your paintbrush in coffee instead of the paint water. It was also the day we secretly accepted that we both probably suck at art. Bwahahaha! All the best Anushrii. It was fun karaokeing white boy music with you. I hope you had a great time here. See you soon!", photo: "/photos/om.png", color: "hsl(270,30%,40%)" },
  { id: 10, from: "Anuj", text: "From you Desi Patakha", fullText: "It was great having you as a friend in a city of strangers, it would've been better if we spent more time together! For our love for Hindi Cinema, I'd say - Tusi jaa rahe ho! Tusi na jao🥺", photo: "/photos/anuj.png", color: "hsl(270,30%,40%)" },
  { id: 11, from: "Narendra", text: "To amazing friendships like these", fullText: "Never imagined growing this close to someone in just few months. Someone Dearest who is from across the oceans — those long beach talks, cooking together, my first 10k — you're forever part of me. I'll cherish every moment and remember you as a happy soul with young eyes, vintage heart, and beautiful mind. Grateful that we're friends & will be through every thick and thin, distance or not. ✨ Keep smiling,Take Care Anu..", photo: "/photos/narendra.png", color: "hsl(270,30%,40%)" },
  { id: 12, from: "Aadya", text: "More than just a work wife", fullText: "I’m going to miss giggling and chatting with you 24/7 while making matcha, drinking chai, going on walks and goofing around at old street. I’m kinda mad i won’t get to hang out with you everyday now :/ but I’m so glad I’ve gotten to know you :) so excited for what’s in store for you (year of the HORSE!) Keep visiting! mwah xx", photo: "/photos/aadya.png", color: "hsl(270,30%,40%)" },
  { id: 13, from: "Vidisha", text: "", fullText: "", photo: "/photos/vidi.png", color: "hsl(270,30%,40%)" },
  { id: 14, from: "Yash", text: "TEENAGE DIRTBAG twin", fullText: "From the first clubbing out where I yelled WASSUP NI**AS and later showered puke to make such great FIRST IMPRESSION. To being your FRAT HOUSE's SLAYEST ROOMIE, we have made so much memories it still feels like I STILL NEED MORE TIME AND KARAOKE WITH YOUUUU .... This for sure isnt a goodbye but SLAYY GURLL until WE MEET AGAIN !!!", photo: "/photos/yash.png", color: "hsl(270,30%,40%)" },
  { id: 14, from: "Shree", text: "", fullText: "", photo: "/photos/shree.png", color: "hsl(270,30%,40%)" },
];
